### PR TITLE
openssh 7.5p1

### PR DESCRIPTION
**Pull request by yurikoles**
It seems like patch for launchd is shipping upstream.

### CODE REVIEW

**Comment by yurikoles** [comment]
I had removed libressl due to audit complain.

```
$ brew audit homebrew/dupes/openssh --online
homebrew/dupes/openssh:
  * Formulae should not depend on both OpenSSL and LibreSSL (even optionally).
Error: 1 problem in 1 formula
```

**Comment by alex** [comment]
test failure looks to be intermittent

**Comment by tdsmith** [comment]
Thanks for your pull request! :tada: Homebrew thrives because of contributions like this one.

**Comment by yurikoles** [comment]
@tdsmith you are welcome!

**Pull request closed without merging**
