### PR TITLE
lsof 4.89

### PR DESCRIPTION
**Pull request by sjackman**
Both previous mirrors no longer work.

### CODE REVIEW

**Comment by sjackman** [comment]
```
cc  -DHASIPv6 -mdynamic-no-pic -DHASUTMPX -DDARWINV=1200 -DHAS_STRFTIME -DLSOF_VSTR="15.4.0" -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -O   -c -o ckkv.o ckkv.c
dfile.c:289:14: error: expected expression
            putchar(`,');
                    ^
dfile.c:289:16: error: expected expression
            putchar(`,');
                      ^
dfile.c:335:6: error: void function 'print_nm' should not return a value [-Wreturn-type]
            return(1);
            ^     ~~~
```
http://bot.brew.sh/job/Homebrew%20Dupes%20Pull%20Requests/260/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_homebrew_dupes_lsof/

**Comment by DomT4** [comment]
Prior discussion in https://github.com/Homebrew/homebrew-dupes/pull/537.

**Comment by DomT4** [comment]
"Fixed" via https://github.com/Homebrew/homebrew-dupes/commit/034cf0f5aad367bc3d1c8f883b7fd8b41a2748d2 for now, until we can sort out the upgrade situation.

**Comment by ilovezfs** [comment]
Interestingly 4.89 installs fine on OS X 10.8

**Comment by ilovezfs** [comment]
https://gist.github.com/ilovezfs/96411ecd23c80c9ed2dddcc9656a759c

**Comment by DomT4** [comment]
That's interesting.

Something about newish Clangs then possibly? Everything above 10.9 is failing, which takes us back to around Clang 5.1, LLVM 3.4, which 10.8 shipped with.

**Comment by DomT4** [comment]
Wonder if it fails with a modern GNU GCC on OS X.

**Comment by ilovezfs** [comment]
I'll poke at it a bit.

**Comment by ilovezfs** [comment]
Builds against the 10.8 SDK on 10.11. Isn't that just precious?

GCC, no difference.

**Comment by ilovezfs** [comment]
@DomT4 Fixed:
```
diff --git a/lsof.rb b/lsof.rb
index 0929a4e..d2925b0 100644
--- a/lsof.rb
+++ b/lsof.rb
@@ -1,9 +1,8 @@
 class Lsof < Formula
   desc "Utility to list open files"
   homepage "https://people.freebsd.org/~abe/"
-  url "ftp://sunsite.ualberta.ca/pub/Mirror/lsof/lsof_4.88.tar.bz2"
-  mirror "http://mirror.jaredwhiting.net/distfiles/lsof_4.88.tar.bz2"
-  sha256 "fe6f9b0e26b779ccd0ea5a0b6327c2b5c38d207a6db16f61ac01bd6c44e5c99b"
+  url "https://mirrorservice.org/sites/lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_4.89.tar.bz2"
+  sha256 "81ac2fc5fdc944793baf41a14002b6deb5a29096b387744e28f8c30a360a3718"
 
   bottle do
     cellar :any_skip_relocation
@@ -22,7 +21,9 @@ class Lsof < Formula
       inreplace %w[dialects/darwin/kmem/dlsof.h dialects/darwin/kmem/machine.h
                    dialects/darwin/libproc/machine.h],
                 "/usr/include", MacOS.sdk_path.to_s + "/usr/include"
-
+      inreplace %w[dialects/darwin/libproc/dstore.c
+                   dialects/darwin/libproc/dfile.c],
+                "PROC_FP_GUARDED", "OPROC_FP_GUARDED"
       mv "00README", "../README"
       system "./Configure", "-n", "darwin"
       system "make"

```

Explanation:
```
iMac-TMP:SDKs joe$ diff MacOSX10.{8,11}.sdk/usr/include/sys/proc_info.h |grep GUARD
> #define PROC_FP_GUARDED	4	/* guarded fd */
> #define PROC_FI_GUARD_CLOSE		(1u << 0)
> #define PROC_FI_GUARD_DUP		(1u << 1)
> #define PROC_FI_GUARD_SOCKET_IPC	(1u << 2)
> #define PROC_FI_GUARD_FILEPORT		(1u << 3)

```

**Comment by DomT4** [comment]
Nice sleuthing! That `inreplace` works fine on 10.8 as well, I presume? If you can find somewhere upstream to report it to feel free to submit and merge a PR here to do that.

**Comment by ilovezfs** [comment]
Thanks.

Yes the inreplace would work the same regardless. OPROC_FP_GUARDED is just intended as nonsense that won't be defined anywhere, as opposed to PROC_FP_GUARDED which is newly defined apparently for >= 10.9.

That said, I think we might as well fix the new code that's been dragged in since Apple defined PROC_FP_GUARDED. Only changes need to get it compiling are putchar(',') and declaring `extern struct pff_tab Pgf_tab[];` in dfile.c

**Pull request closed without merging**
