### PR TITLE
openldap 2.4.40

### PR DESCRIPTION
**Pull request by DomT4**
Version bump, style nits.

Quite a few headers shadow the system, but I presume that's known and folks are happy with not sandboxing against that more.

### CODE REVIEW

**Comment by DomT4** [comment]
Expected errors:

```
==> brew audit Homebrew/dupes/openldap					 FAILED
Error: 1 problems in 1 formulae
openldap:
 * Header files that shadow system header files were installed to "/usr/local/Cellar/openldap/2.4.40/include"
The offending files are:
  /usr/local/Cellar/openldap/2.4.40/include/lber.h
  /usr/local/Cellar/openldap/2.4.40/include/lber_types.h
  /usr/local/Cellar/openldap/2.4.40/include/ldap.h
  /usr/local/Cellar/openldap/2.4.40/include/ldap_cdefs.h
  /usr/local/Cellar/openldap/2.4.40/include/ldap_features.h
  /usr/local/Cellar/openldap/2.4.40/include/ldap_schema.h
  /usr/local/Cellar/openldap/2.4.40/include/ldap_utf8.h
  /usr/local/Cellar/openldap/2.4.40/include/ldif.h
  /usr/local/Cellar/openldap/2.4.40/include/slapi-plugin.h
```

Unexpected and unreproducible locally errors:

```
==> brew install ./openldap-2.4.40.mavericks.bottle.tar.gz		 FAILED
==> Installing openldap from Homebrew/homebrew-dupes
==> Pouring openldap-2.4.40.mavericks.bottle.tar.gz
Error: Permission denied - /usr/local/etc/openldap/schema/collective.ldif
```

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by plessbd** [comment]
How does one get the bottle?

```
brew install openldap
==> Installing openldap from homebrew/homebrew-dupes
==> Downloading ftp://ftp.openldap.org/pub/OpenLDAP/openldap-release/openldap-2.4.40.tgz
Already downloaded: /Library/Caches/Homebrew/openldap-2.4.40.tgz
==> ./configure --prefix=/Volumes/750GBHD/usr/local/Cellar/openldap/2.4.40 --sysconfdir=/Volumes/750GBHD/usr/local/etc --localstatedir=/Volumes/750GBHD/usr/local/var --enable-bdb=no --enable-hdb=no
==> make install
🍺  /Volumes/750GBHD/usr/local/Cellar/openldap/2.4.40: 131 files, 7.1M, built in 117 seconds
```

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Get the same thing locally:

```
==> Pouring openldap-2.4.40.yosemite.bottle.tar.gz
tar xf /Users/Dominyk/Downloads/openldap-2.4.40.yosemite.bottle.tar.gz
Error: Permission denied - /usr/local/etc/openldap/schema/collective.ldif
```

```
~> ls -lh /usr/local/etc/openldap/schema/collective.ldif
-r--r--r-- 1 Dominyk admin 2.0K Jun 24 01:11 /usr/local/etc/openldap/schema/collective.ldif
```

```
rm /usr/local/etc/openldap/schema/collective.ldif
override r--r--r--  Dominyk/admin for /usr/local/etc/openldap/schema/collective.ldif?
```

Get rid of that file and you just hit:

```
tar xf /Users/Dominyk/Downloads/openldap-2.4.40.yosemite.bottle.tar.gz
Error: Permission denied - /usr/local/etc/openldap/schema/collective.schema
```

```
ls -lh /usr/local/etc/openldap/schema/collective.schema
-r--r--r-- 1 Dominyk admin 6.1K Jun 24 01:11 /usr/local/etc/openldap/schema/collective.schema
```

So that's fun.

**Comment by DomT4** [comment]
Can apparently be fixed by running `chmod 0755` on *everything* inside `/usr/local/etc/openldap`. Whether that's something we want to do or not is questionable.

**Comment by DomT4** [comment]
Pushed the change here, which passed the build finally. The `audit` warning on shadowed headers is the only failure now. Will defer to you on how happy we are with `chmod`-ing configuration directories and everything in them.

**Comment by jacknagel** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
