### PR TITLE
openssh 7.2p2

### PR DESCRIPTION
**Pull request by alex**
Fixes #575 

Resolves: http://www.openssh.com/txt/x11fwd.adv

### CODE REVIEW

**Comment by alex** [comment]
Oof, the lauchd patch no longer applies cleanly, and it's not obvious to me how to fix.

**Comment by DomT4** [comment]
I updated the patches in our patches repo if you wish to apply those changes. Can see an example [here](https://github.com/DomT4/homebrew-crypto/commit/2890431364244f39c11fd953d8142d20efe147ff).

**Comment by alex** [comment]
@DomT4 attempted to mimic that

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-dupes/commit/23de1c4c3f848e69ce7dcb42f01c9bd8f6d12e1f. Thank you for another contribution to Homebrew @alex! :smiley:

**Pull request closed without merging**
