### PR TITLE
Update tcl-tk.rb

### LINKED ISSUE #490: Tcl-tk link broken
The current tk src link is broken in tcl-tk.rb.

### PR DESCRIPTION
**Pull request by charle692**
Fixes #490.

### CODE REVIEW

**Comment by charle692** [comment]
It seems like https one Sourceforge is no longer working and causes issues when trying to install tcl-tk.

**Comment by dunn** [comment]
The `https` url is working for me:
```
🐙  curl -IL https://downloads.sourceforge.net/project/tcl/Tcl/8.6.4/tk8.6.4-src.tar.gz
HTTP/1.1 302 Found
Server: nginx
Date: Tue, 21 Jul 2015 19:43:04 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
content-disposition: attachment; filename="tk8.6.4-src.tar.gz"
Set-Cookie: sf_mirror_attempt="tcl:iweb:Tcl/8.6.4/tk8.6.4-src.tar.gz"; expires=120; Path=/
Location: http://iweb.dl.sourceforge.net/project/tcl/Tcl/8.6.4/tk8.6.4-src.tar.gz

HTTP/1.1 200 OK
Date: Tue, 21 Jul 2015 19:43:04 GMT
Server: Apache
Last-Modified: Thu, 12 Mar 2015 14:14:06 GMT
ETag: "142582e-4119ba-51117ff23a780"
Accept-Ranges: bytes
Content-Length: 4266426
Connection: close
Content-Type: application/x-gzip
```

**Comment by dunn** [comment]
While you've got the PR open, though, would you like to fix these audit warnings?
```
 * A top-level "man" directory was found
Homebrew requires that man pages live under share.
This can often be fixed by passing "--mandir=#{man}" to configure.
 * Non-libraries were installed to "/usr/local/Cellar/tcl-tk/8.6.4/lib"
Installing non-libraries to "lib" is discouraged.
The offending files are:
  /usr/local/Cellar/tcl-tk/8.6.4/lib/Tk.icns
  /usr/local/Cellar/tcl-tk/8.6.4/lib/Tk.tiff
```

**Comment by charle692** [comment]
Mmm might be doing this wrong. I've included a photo of what is happening. 
selection_001

**Comment by DomT4** [comment]
Seems to be a local issue for you. I can't reproduce here. It may be that the particular mirror you hit is having issues; Can you try a fresh `brew fetch tcl-tk -fs -v`?

**Comment by charle692** [comment]
It seems to be working now. Not sure what was causing it though. Must of been a problem reaching a mirror like you said.

**Comment by DomT4** [comment]
Cool. I suspect either SF or the mirror was having some sort of issue, we seem to hit temporarily "dud" mirrors from time to time. Closing here but feel free to flag it up if it happens again, Thanks!

**Pull request closed without merging**
