### PR TITLE
Add `desc` entries to all formulae missing them

### PR DESCRIPTION
**Pull request by hivehand**
I hope I’ve properly observed Homebrew’s one-commit-per-formula and “\<name\>: \<changes\>” commit-message conventions.

### CODE REVIEW

**Comment by hivehand** [comment]
@dunn, I see that you killed the test. I’m sorry — did I, despite my best intentions, botch the commits and/or their messages horribly?

**Comment by dunn** [comment]
Sorry, should've explained. Building all of those formulae would have taken more than the 65 minutes we give the test-bot, so it was going to fail anyway.  If none of the other maintainers have any objections to the changes, we can either bump the timeout and run the builds again or just merge.

**Comment by hivehand** [comment]
Ah, gotcha! Thanks for the explanation. (Is there a preferred way, should I ever find myself wanting to make small changes to a large number of files, to submit the corresponding pull request(s)?)

**Comment by dunn** [comment]
I guess it's best to open an issue first, to give us a heads-up; then we can decide if it needs to be run against the test-bot and whne.

**Comment by apjanke** [comment]
Looks low risk, and `brew info` runs on all of them for me, so we know it didn't introduce any syntax errors. Want to just rebase on `master` and we'll merge w/o doing the full test?

**Comment by manphiz** [comment]
Looks good to merge without bothering the testing bots.

**Comment by sjackman** [comment]
Bump. Merge?

**Comment by apjanke** [comment]
I hate to say it, but it looks like this PR is no longer needed; someone's added `desc`s to all the `homebrew-dupes` formulae in the mean time.

Sorry for the duplicated work. Thank you for your contribution to Homebrew, regardless!

**Pull request closed without merging**
