### PR TITLE
tcpdump 4.9.0

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
@ilovezfs Any chance you can merge this one in? ❤️. Current version has known security issues, because, well, software in 2017.

**Comment by ilovezfs** [comment]
Done.

**Comment by ilovezfs** [comment]
@neutric thanks! :1st_place_medal:

**Comment by ilovezfs** [comment]
Your wish is my command.

**Comment by DomT4** [comment]
I'll dump some PRs on you in core as a thank you 😈

**Comment by ilovezfs** [comment]
@DomT4 take a look at the science queue :)

**Comment by DomT4** [comment]
@ilovezfs I see not much has changed on the Science CI side of things 😄

**Comment by ilovezfs** [comment]
We have a _wonderful_ new innovation over there: Linux bottles via Circle CI.

**Comment by DomT4** [comment]
*Brings out list of reasons to keep politely declining a return, adds another line* 😉

**Comment by ilovezfs** [comment]
LOL. What if I say pretty please with sugar on top? haha

**Comment by DomT4** [comment]
You get a lot more freedom without me around. I wouldn't want to deprive you of that 😸

**Comment by ilovezfs** [comment]
_Agrees to work while in a cage_

**Comment by neutric** [comment]
:)

**Pull request closed without merging**
