### PR TITLE
krb5 1.13: New formula

### PR DESCRIPTION
**Pull request by sjackman**
MIT Kerberos: The Network Authentication Protocol

### CODE REVIEW

**Comment by sjackman** [comment]
@jacknagel Bump

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by sjackman** [comment]
[Log](http://bot.brew.sh/job/Homebrew%20Dupes%20Pull%20Requests/64/version=yosemite/testReport/junit/brew-test-bot/yosemite/audit_Homebrew_dupes_krb5___strict/)
```
failed: brew audit Homebrew/dupes/krb5 --strict
Stacktrace

        ==> brew style krb5

1 file inspected, no offenses detected
Error: 1 problems in 1 formulae

==> audit problems
krb5:
 * Stable: SHA1 checksums are deprecated, please use SHA256
```

**Comment by sjackman** [comment]
Change SHA1 to SHA256.

**Comment by sjackman** [comment]
Thanks, Jack.

**Pull request closed without merging**
