### PR TITLE
lsof 4.89

### PR DESCRIPTION
**Pull request by crlf0710**

### CODE REVIEW

**Comment by DomT4** [comment]
Install died on all three platforms: http://bot.brew.sh/job/Homebrew%20Dupes%20Pull%20Requests/175/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_homebrew_dupes_lsof/

**Comment by crlf0710** [comment]
i think we should patch the line
    putchar(`,');
to 
    putchar(',');

how can i patch a file inside an archive inside an archive?

**Comment by DomT4** [comment]
You could use an `inreplace`. What do you mean with the nested archive? As in when the build begins there's something like this:

```
- buildpath
-- Configure
-- Other files
-- archive.tar.gz
```
Or such?

**Comment by apjanke** [comment]
Even if this is fixed, there are other bugs in the Darwin code in 4.89. I added the `inreplace` to fix that typo and got this, due to a missing variable declaration in the header files.

```
cc  -DHASIPv6 -mdynamic-no-pic -DHASUTMPX -DDARWINV=1300 -DHAS_STRFTIME -DLSOF_VSTR=\"13.4.0\" -I/Applications/Xcode-6.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include  -I/Applications/Xcode-6.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -O   -c -o dfile.o dfile.c
dfile.c:295:11: error: use of undeclared identifier 'Pgf_tab'
            tp = Pgf_tab;
                 ^
1 error generated.
make: *** [dfile.o] Error 1
```

Maybe we should just skip version 4.89.

**Comment by DomT4** [comment]
Any idea if someone's dinged upstream about that?

**Comment by apjanke** [comment]
I emailed them, using the address on the home page. I don't see any public list or bug tracker.

**Comment by apjanke** [comment]
If people rally care about `lsof`on OS X, maybe someone could volunteer as a tester for upstream. It seems they didn't compile this release on OS X before shipping, much less test its behavior.
(That's not a criticism of the developer; they probably just don't have a Mac to test on.)

**Comment by sjackman** [comment]
Both `url` and `mirror` are dead links. Working URLs can be found in #601

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-dupes/pull/616.

**Pull request closed without merging**
