### PR TITLE
xar: migrate from Homebrew/Homebrew

### PR DESCRIPTION
**Pull request by DomT4**
Re: https://github.com/Homebrew/homebrew/pull/36418

### CODE REVIEW

**Comment by DomT4** [comment]
The test-bot tested the version in Homebrew/Homebrew rather than this PR, hence the failure.

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by jacknagel** [comment]
>The test-bot tested the version in Homebrew/Homebrew rather than this PR, hence the failure.

I think Mike fixed this, so kicking off another build.

**Comment by DomT4** [comment]
Yup, Looks like it :+1:. The SHA needs fixing for it to pass the ` audit --strict ` but otherwise looks good on the bot.

**Pull request closed without merging**
