### PR TITLE
openldap: Berkeley DB 4.4 - 4.8 or 5.0 - 5.1 is required.

### PR DESCRIPTION
**Pull request by lembacon**

### CODE REVIEW

**Comment by DomT4** [comment]
Can you provide build-logs showing the failure on the existing option?

**Comment by lembacon** [comment]
@DomT4 Sorry for the late reply. Here are the build logs https://gist.github.com/13fd76767a107053f0b5

`configure: error: BerkeleyDB version incompatible with BDB/HDB backends` is the fatal error.

**Comment by DomT4** [comment]
Alright, seems reasonable. Let's just make it `depends_on "berkeley-db4" => :optional` though.

**Comment by lembacon** [comment]
@DomT4 Fixed via https://github.com/Homebrew/homebrew-dupes/commit/bc961fb95b027db795350caa40cec6b5db6c8543 :smiley_cat:

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-dupes/commit/2e9c4ff60093cbe178bc3a5782988a6a1895010e. Thank you for your contribution to Dupes, we appreciate it! :smiley_cat:

**Pull request closed without merging**
