### PR TITLE
file-formula: Use magic.mgc and libs of libmagic

### PR DESCRIPTION
**Pull request by sjackman**
Both `libmagic` and `file-formula` install the magic database `magic.mgc`. The user would have to update both databases if they were to add custom recipes. This patch eliminates this duplication.

Before this patch
```sh
❯❯❯ /usr/local/Cellar/file-formula/5.25/bin/file -v
file-5.25
magic file from /usr/local/Cellar/file-formula/5.25/share/misc/magic
```

After this patch
```sh
❯❯❯ /usr/local/Cellar/file-formula/5.25/bin/file -v
file-5.25
magic file from /usr/local/Cellar/libmagic/5.25/share/misc/magic
```

### CODE REVIEW

**Comment by sjackman** [comment]
Only two files are installed:
```
bin/file
share/man/man1/file.1
```

**Comment by apjanke** [comment]
:+1:

Something's wrong with the bottle build; maybe because the Jenkins run aged out.

@BrewTestBot test this please.

**Comment by sjackman** [comment]
Thanks for merging, Andrew!

**Comment by ilovezfs** [comment]
@sjackman it looks like I may need to revert this because it's causing audit failure now:
https://bot.brew.sh/job/Homebrew%20Dupes%20Pull%20Requests/354/version=sierra/console

**Comment by ilovezfs** [comment]
@sjackman OK, it looks like this diff will allow us to preserve your changes:
```
diff --git a/file-formula.rb b/file-formula.rb
index 826bc84..ae79821 100644
--- a/file-formula.rb
+++ b/file-formula.rb
@@ -18,7 +18,11 @@ class FileFormula < Formula
 
   depends_on "libmagic"
 
+  patch :DATA
+
   def install
+    ENV.prepend "LDFLAGS", "-L#{Formula["libmagic"].opt_lib} -lmagic"
+
     system "./configure", "--disable-dependency-tracking",
                           "--prefix=#{prefix}"
     system "make", "install-exec"
@@ -30,3 +34,26 @@ class FileFormula < Formula
     system "#{bin}/file", test_fixtures("test.mp3")
   end
 end
+
+__END__
+diff --git a/src/Makefile.in b/src/Makefile.in
+index b6eeb20..4a7ae91 100644
+--- a/src/Makefile.in
++++ b/src/Makefile.in
+@@ -150,7 +150,6 @@ libmagic_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
+ PROGRAMS = $(bin_PROGRAMS)
+ am_file_OBJECTS = file.$(OBJEXT)
+ file_OBJECTS = $(am_file_OBJECTS)
+-file_DEPENDENCIES = libmagic.la
+ AM_V_P = $(am__v_P_@AM_V@)
+ am__v_P_ = $(am__v_P_@AM_DEFAULT_V@)
+ am__v_P_0 = false
+@@ -352,7 +351,7 @@ libmagic_la_LDFLAGS = -no-undefined -version-info 1:0:0
+ @MINGW_TRUE@MINGWLIBS = -lgnurx -lshlwapi
+ libmagic_la_LIBADD = $(LTLIBOBJS) $(MINGWLIBS)
+ file_SOURCES = file.c
+-file_LDADD = libmagic.la
++file_LDADD = $(LDADD)
+ CLEANFILES = magic.h
+ EXTRA_DIST = magic.h.in
+ HDR = $(top_srcdir)/src/magic.h.in
```

**Pull request closed without merging**
