### PR TITLE
zlib: revision bump

### PR DESCRIPTION
**Pull request by javian**
Create bottles for Sierra and El Capitan

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Note: likely obsoleted by https://github.com/Homebrew/homebrew-dupes/pull/701

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
We can do this through the homebrew testing job

**Comment by ilovezfs** [comment]
1.2.8 bottles added in https://github.com/Homebrew/homebrew-dupes/commit/ded3d4fd19402a232e9069fce17f24b55f205194.

**Pull request closed without merging**
