### PR TITLE
tcl-tk: don't apply patch for sqlite on Linux machines

### PR DESCRIPTION
**Pull request by maxim-belkin**
In a Linux fork of Homebrew, `MacOS.version` returns `0` and, therefore, simple check `MacOS.version < :something` always true on a Linux machine. This fix makes the patch for sqlite inside the tcl-tk formula work only on Mac machines only.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
I guess it is easier to make `MacOS.version` on Linux return `9999` xP

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
@sjackman Was a decision ever made on the status of `dupes` for Linuxbrew?

**Comment by sjackman** [comment]
So far small changes like this one have been accepted into Homebrew/dupes. There are similar patches in `ncurses`, `openssh` and `rsync`.

Maxim, I was able to install `brew install tcl-tk --without-tk` without needing this patch. Is that because I used `--without-tk`, or because I already had `sqlite` installed?
Does `brew install sqlite tcl-tk` fix your issue?
Please report `brew gist-logs tcl-tk` without this patch applied.

**Comment by DomT4** [comment]
> So far small changes like this one have been accepted into Homebrew/dupes.

Aye, I'm not unhappy to accept small changes like this. Was more curious as to whether there had been more thought on integrating `homebrew/dupes` into Linuxbrew core more and blacklisting this tap, given Linuxbrew needs quite a bit from it and they aren't often dupes on that platform.

**Comment by sjackman** [comment]
I've already pulled a select few formula like `zlib` into Linuxbrew/core that are dependencies of the compiler toolchain `glibc` and `gcc`. I'd rather not have to periodically copy over the commits from Homebrew/dupes into Linuxbrew/core, although it could likely be automated. Homebrew-dupes doesn't really change the often anyway.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-dupes/commit/5df8b5560eed14096e3ce2bd3865a7c297d5fcdb. Thanks @maxim-belkin! :smiley:

**Pull request closed without merging**
