### PR TITLE
zlib 1.2.9

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
New upstream release.  Drop clang patch which is now incorporated upstream.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by rleigh-codelibre** [comment]
1.2.10 is now out after some bugs were discovered, so I'll reopen a new PR once it's on the mirrors.

**Comment by ilovezfs** [comment]
@rleigh-codelibre no need to wait for the mirrors

**Comment by rleigh-codelibre** [comment]
I mean, it's not up on sourceforge itself yet.  Should be later on today.

**Comment by ilovezfs** [comment]
That's fine. As long as http://zlib.net/zlib-1.2.10.tar.gz is good.

**Comment by rleigh-codelibre** [comment]
Superseded by https://github.com/Homebrew/homebrew-dupes/pull/703

**Pull request closed without merging**
