### PR TITLE
openssh 7.1p2

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Resolves this issue: http://undeadly.org/cgi?action=article&sid=20160114142733

**Comment by jomo** [comment]
Looks like [Jenkins](http://bot.brew.sh/job/Homebrew%20Dupes%20Pull%20Requests/213/) has some issues?
> Build has been executing for 1 hr 24 min on master

Don't have any experience with it, but it seems like it's trying to pull in #561 which fails and breaks the build?

**Comment by alex** [comment]
Tests failed, but it doesn't look related?

**Comment by tdsmith** [comment]
Thanks, Alex!

**Pull request closed without merging**
